# Generated by Django 5.0 on 2023-12-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasks',
        ),
    ]
